//! Writes the embedded QML into the directory Quickshell loads.
//!
//! The binary embeds `qml/` at compile time. At startup the core files and the
//! enabled modules are written out, and anything else in the directory is
//! removed. Files whose content didn't change are left alone, because
//! Quickshell reloads whenever a watched file changes.
//!
//! In symlink mode the entries point at the source tree instead, so editing
//! the QML in the repository hot-reloads the running shell.

use std::fs;
use std::io::{self, ErrorKind};
use std::os::unix::fs::symlink;
use std::path::{Path, PathBuf};

use include_dir::{Dir, DirEntry, include_dir};

static QML: Dir = include_dir!("$CARGO_MANIFEST_DIR/qml");
const SOURCE: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/qml");

/// Generated at the shell root. Never instantiated: Quickshell only watches
/// directories that some QML file imports, and module views are loaded by URL
/// at runtime. Importing every module here makes their files hot-reload.
const MODULES_FILE: &str = "Modules.qml";

#[derive(Debug, Clone, Copy)]
pub enum Mode {
    Copy,
    Symlink,
}

pub fn has_module(module: &str) -> bool {
    QML.get_dir(format!("modules/{module}")).is_some()
}

pub fn has_view(module: &str, view: &str) -> bool {
    QML.get_file(format!("modules/{module}/{view}.qml"))
        .is_some()
}

/// Returns how many files were written or relinked.
pub fn write_shell(out: &Path, modules: &[String], mode: Mode) -> io::Result<usize> {
    for module in modules {
        if !has_module(module) {
            return Err(io::Error::new(
                ErrorKind::NotFound,
                format!("unknown module {module}"),
            ));
        }
    }

    fs::create_dir_all(out.join("modules"))?;
    let mut written = 0;

    let mut keep = vec!["modules".to_owned(), MODULES_FILE.to_owned()];
    for entry in QML.entries() {
        if entry.path() == Path::new("modules") {
            continue;
        }
        written += place(entry, out, mode)?;
        keep.push(file_name(entry.path()));
    }
    remove_others(out, &keep)?;

    for module in modules {
        let dir = QML
            .get_dir(format!("modules/{module}"))
            .expect("checked above");
        written += place(&DirEntry::Dir(dir.clone()), out, mode)?;
    }
    remove_others(&out.join("modules"), modules)?;

    if write_if_changed(&out.join(MODULES_FILE), modules_file(modules).as_bytes())? {
        written += 1;
    }

    Ok(written)
}

fn modules_file(modules: &[String]) -> String {
    let mut text = String::from(
        "// Generated by mochi. Do not edit.\n\
         // Imports every module so Quickshell watches their files for hot reload.\n\
         import QtQuick\n",
    );
    for (index, module) in modules.iter().enumerate() {
        text.push_str(&format!("import \"modules/{module}\" as Module{index}\n"));
    }
    text.push_str("\nQtObject {}\n");
    text
}

fn place(entry: &DirEntry, out: &Path, mode: Mode) -> io::Result<usize> {
    match mode {
        Mode::Copy => copy(entry, out),
        Mode::Symlink => link(entry, out),
    }
}

fn link(entry: &DirEntry, out: &Path) -> io::Result<usize> {
    let target = out.join(entry.path());
    let source = Path::new(SOURCE).join(entry.path());

    if fs::read_link(&target).is_ok_and(|current| current == source) {
        return Ok(0);
    }
    remove(&target)?;
    symlink(&source, &target)?;
    Ok(1)
}

fn copy(entry: &DirEntry, out: &Path) -> io::Result<usize> {
    let target = out.join(entry.path());
    match entry {
        DirEntry::File(file) => Ok(usize::from(write_if_changed(&target, file.contents())?)),
        DirEntry::Dir(dir) => {
            if is_symlink(&target) {
                remove(&target)?;
            }
            fs::create_dir_all(&target)?;

            let mut written = 0;
            let mut keep = Vec::new();
            for child in dir.entries() {
                written += copy(child, out)?;
                keep.push(file_name(child.path()));
            }
            remove_others(&target, &keep)?;
            Ok(written)
        }
    }
}

/// Writes through a temporary file and a rename, so Quickshell never reads a
/// half-written file. Returns whether anything was written.
fn write_if_changed(path: &Path, contents: &[u8]) -> io::Result<bool> {
    if is_symlink(path) {
        remove(path)?;
    } else if fs::read(path).is_ok_and(|current| current == contents) {
        return Ok(false);
    }

    let mut temporary = path.as_os_str().to_owned();
    temporary.push(".tmp");
    let temporary = PathBuf::from(temporary);

    fs::write(&temporary, contents)?;
    fs::rename(&temporary, path)?;
    Ok(true)
}

fn remove_others(dir: &Path, keep: &[String]) -> io::Result<()> {
    for entry in fs::read_dir(dir)? {
        let entry = entry?;
        if !keep.iter().any(|name| entry.file_name() == name.as_str()) {
            remove(&entry.path())?;
        }
    }
    Ok(())
}

/// Removes a file, symlink or directory. Missing paths are fine.
fn remove(path: &Path) -> io::Result<()> {
    let result = match fs::symlink_metadata(path) {
        Ok(metadata) if metadata.is_dir() => fs::remove_dir_all(path),
        Ok(_) => fs::remove_file(path),
        Err(error) => Err(error),
    };
    match result {
        Err(error) if error.kind() == ErrorKind::NotFound => Ok(()),
        other => other,
    }
}

fn is_symlink(path: &Path) -> bool {
    fs::symlink_metadata(path).is_ok_and(|metadata| metadata.is_symlink())
}

fn file_name(path: &Path) -> String {
    path.file_name()
        .expect("embedded paths have a file name")
        .to_string_lossy()
        .into_owned()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn scratch(name: &str) -> PathBuf {
        let dir = std::env::temp_dir().join(format!("mochi-spike-{name}-{}", std::process::id()));
        let _ = fs::remove_dir_all(&dir);
        dir
    }

    fn modules(names: &[&str]) -> Vec<String> {
        names.iter().map(|name| name.to_string()).collect()
    }

    #[test]
    fn second_write_changes_nothing() {
        let out = scratch("idempotent");
        let first = write_shell(&out, &modules(&["idle", "demo"]), Mode::Copy).unwrap();
        assert!(first > 0);
        assert_eq!(
            write_shell(&out, &modules(&["idle", "demo"]), Mode::Copy).unwrap(),
            0
        );
        fs::remove_dir_all(out).unwrap();
    }

    #[test]
    fn disabled_modules_are_removed() {
        let out = scratch("disable");
        write_shell(&out, &modules(&["idle", "demo"]), Mode::Copy).unwrap();
        write_shell(&out, &modules(&["idle"]), Mode::Copy).unwrap();

        assert!(out.join("modules/idle/Pill.qml").exists());
        assert!(!out.join("modules/demo").exists());
        let generated = fs::read_to_string(out.join(MODULES_FILE)).unwrap();
        assert!(!generated.contains("modules/demo"));
        fs::remove_dir_all(out).unwrap();
    }

    #[test]
    fn switching_modes_replaces_entries() {
        let out = scratch("modes");
        write_shell(&out, &modules(&["idle"]), Mode::Symlink).unwrap();
        assert!(is_symlink(&out.join("island")));

        write_shell(&out, &modules(&["idle"]), Mode::Copy).unwrap();
        assert!(!is_symlink(&out.join("island")));
        assert!(out.join("island/Island.qml").is_file());
        fs::remove_dir_all(out).unwrap();
    }

    #[test]
    fn unknown_module_is_an_error() {
        let out = scratch("unknown");
        assert!(write_shell(&out, &modules(&["nope"]), Mode::Copy).is_err());
    }
}
