[package]
name = "mochi"
description = "Command-line client for the Mochi daemon"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
clap.workspace = true
clap_complete.workspace = true
mochi-plugins.workspace = true
mochi-protocol.workspace = true
serde.workspace = true
serde_json.workspace = true

[lints]
workspace = true
